services:
  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: 128

  inference-server:
    build: .
    depends_on:
      - vector-db
    ports:
      - "9000:9000"
    environment:
       QDRANT_API_KEY: ${QDRANT_API_KEY}
